# Generated by Django 2.2.3 on 2019-07-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konacademy', '0004_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
        migrations.AddField(
            model_name='book',
            name='asset',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
